In [1]:
from pytorch_toolz.functools import Parallel, Reduce, Sequential
from pytorch_toolz.operator import Apply
from pytorch_toolz.itertools import Accumulate
from torch import nn
import torch

In [2]:
lstm_swap_args = Sequential(Apply(lambda *args: reversed(args)), nn.LSTMCell(8, 8), unpack=True)

In [5]:
rnn = Accumulate(
    lstm_swap_args,
    initial=(torch.zeros(8),torch.zeros(8))
)

In [7]:
seq = torch.randn(10, 8)

rnn(seq)

((tensor([0., 0., 0., 0., 0., 0., 0., 0.]),
  tensor([0., 0., 0., 0., 0., 0., 0., 0.])),
 (tensor([-0.1169, -0.1231, -0.0435,  0.0198,  0.0099, -0.0187,  0.1105, -0.1274],
         grad_fn=<SqueezeBackward1>),
  tensor([-0.2014, -0.2099, -0.0677,  0.0544,  0.0229, -0.0424,  0.1618, -0.3059],
         grad_fn=<SqueezeBackward1>)),
 (tensor([-0.2002, -0.2166, -0.2359, -0.1195,  0.0066, -0.0417,  0.2290, -0.0610],
         grad_fn=<SqueezeBackward1>),
  tensor([-0.5265, -0.3692, -0.4439, -0.2452,  0.0159, -0.1192,  0.3718, -0.2119],
         grad_fn=<SqueezeBackward1>)),
 (tensor([-0.1117, -0.0792, -0.0294, -0.0389, -0.0587, -0.0109,  0.1151, -0.0082],
         grad_fn=<SqueezeBackward1>),
  tensor([-0.2048, -0.1397, -0.0470, -0.0773, -0.1346, -0.0393,  0.2663, -0.0110],
         grad_fn=<SqueezeBackward1>)),
 (tensor([-0.0747, -0.1049, -0.2728, -0.0056, -0.2044, -0.0609, -0.0762, -0.0974],
         grad_fn=<SqueezeBackward1>),
  tensor([-0.1311, -0.1526, -0.4196, -0.0213, -0.4556, -0.221